# Generated by Django 4.2.6 on 2023-10-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pquantity', models.IntegerField()),
                ('pprice', models.IntegerField()),
                ('pdate', models.DateField()),
                ('ptime', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pdate',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pprice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pquantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ptime',
        ),
    ]
