# Generated by Django 4.2.6 on 2023-10-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_cartdetails_remove_cart_pdate_remove_cart_pprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='productname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
