# Generated by Django 4.2.6 on 2023-11-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_cartdetails_cusname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
